spring.application.name=student-activity
server.port=${PORT:8081}

# MySQL config
spring.datasource.url=${DATABASE_URL:${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/studentdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}}
spring.datasource.username=${DATABASE_USERNAME:${JDBC_DATABASE_USERNAME:root}}
spring.datasource.password=${DATABASE_PASSWORD:${JDBC_DATABASE_PASSWORD:Prasanth@63#7}}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=${JPA_DATABASE_PLATFORM:org.hibernate.dialect.MySQL8Dialect}

# Show SQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Security Logging
logging.level.org.springframework.security=DEBUG
